# Write custom hyprland settings here, such as keyboard layouts, monitor settings, etc.

# example

# windowrulev2 = workspace 21 silent,initialTitle:^(Spotify Premium)$
# windowrulev2 = workspace 21 silent,class:^(Spotify)$

# exec-once = hyprctl dispatch -- exec [workspace 21 silent] spotify
